# hybrid-cluster.yaml
# An example of ClusterConfig containing Windows and Linux node groups to support Windows workloads
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: leonj-demo
  region: ap-southeast-1

managedNodeGroups:
  - name: eks-nodes
    instanceType: t2.large
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    tags:
      nodegroup-role: eks-nodes
