apiVersion: split.smi-spec.io/v1alpha1
kind: TrafficSplit
metadata:
  name: grpc-server-blue
  namespace: default
spec:
  service: grpc-server-blue
  backends:
  - service: grpc-server-v2
    weight: 100