apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-server-v1
  labels:
    app: grpc-server
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
      - name: grpc-server
        image: leonjalfon1/grpc-demo:v1
        ports:
        - containerPort: 50051
          protocol: TCP